/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/evals/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evals Latest */
        get: operations["get_evals_latest_api_evals_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evals/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Eval Results */
        post: operations["post_eval_results_api_evals_results_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ledger Export */
        get: operations["ledger_export_api_ledger_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ledger/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ledger Verify */
        post: operations["ledger_verify_api_ledger_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monitor/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monitor Events */
        get: operations["monitor_events_api_monitor_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monitor/heal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Monitor Heal */
        post: operations["monitor_heal_api_monitor_heal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proof": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Proof */
        get: operations["get_proof_api_proof_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public Key */
        get: operations["public_key_api_public_key_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resolver/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolver Match */
        post: operations["resolver_match_api_resolver_match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Operator Approval */
        post: operations["operator_approval_api_runs__run_id__approval_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream */
        get: operations["stream_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events Json */
        get: operations["events_json_api_runs__run_id__events_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sandbox/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sandbox Runs */
        post: operations["sandbox_runs_api_sandbox_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sandbox/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sandbox Status */
        get: operations["sandbox_status_api_sandbox_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdapterFaultPayload */
        AdapterFaultPayload: {
            /** Call Site */
            call_site: string;
            /** Injected */
            injected: boolean;
            /**
             * Kind
             * @enum {string}
             */
            kind: "timeout" | "rate_limit" | "conflict_409" | "server_5xx";
            /** Ledger Id */
            ledger_id: number;
        };
        /** ApprovalBody */
        ApprovalBody: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "deny";
        };
        /** ApprovalDecided */
        ApprovalDecided: {
            /** Approver Display */
            approver_display: string | null;
            /** Decided At */
            decided_at: string | null;
            /**
             * Decision
             * @enum {string}
             */
            decision: "PENDING" | "APPROVED" | "DENIED" | "EXPIRED";
            /**
             * Mode
             * @enum {string}
             */
            mode: "slack" | "operator" | "sandbox_auto";
        };
        /** ApprovalRequested */
        ApprovalRequested: {
            /** Args Hash */
            args_hash: string;
            /** Expires At */
            expires_at: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "slack" | "operator" | "sandbox_auto";
            /** Slack Channel */
            slack_channel: string | null;
            /** Slack Ts */
            slack_ts: string | null;
            /** Summary */
            summary: string;
        };
        /** ApprovalResult */
        ApprovalResult: {
            /** Decision */
            decision: string;
        };
        /** Candidate */
        Candidate: {
            /** App */
            app: string;
            /** Label */
            label: string;
            /** Score */
            score: number;
        };
        /** EvalResultIn */
        EvalResultIn: {
            /** Description */
            description?: string | null;
            /** Detail */
            detail?: string | null;
            /**
             * Duplicate Writes Prevented
             * @default 0
             */
            duplicate_writes_prevented: number;
            /**
             * Expected Outcome
             * @description Null or empty for a detection scenario, such as chain_tamper, that starts no run.
             */
            expected_outcome?: ("SUCCESS" | "PARTIAL" | "REFUSED" | "NEEDS_HUMAN") | null;
            /**
             * Forbidden Attempted
             * @default 0
             */
            forbidden_attempted: number;
            /**
             * Forbidden Refused
             * @default 0
             */
            forbidden_refused: number;
            /**
             * Observed Outcome
             * @description One outcome, or outcomes joined with '+' when the scenario starts several runs.
             */
            observed_outcome?: string | null;
            /** Passed */
            passed: boolean;
            /** Run Id */
            run_id?: string | null;
            /** Scenario Id */
            scenario_id: string;
        };
        /** EvalRunIn */
        EvalRunIn: {
            /** Commit Sha */
            commit_sha?: string | null;
            /** Results */
            results: components["schemas"]["EvalResultIn"][];
            /** Run At */
            run_at?: string | null;
        };
        /** EvalRunRecorded */
        EvalRunRecorded: {
            /** Batch Id */
            batch_id: string;
            /** Results */
            results: number;
        };
        /** EventAdapterFault */
        EventAdapterFault: {
            /** At */
            at: string;
            payload: components["schemas"]["AdapterFaultPayload"];
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "adapter.fault";
        };
        /** EventApprovalDecided */
        EventApprovalDecided: {
            /** At */
            at: string;
            payload: components["schemas"]["ApprovalDecided"];
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "approval.decided";
        };
        /** EventApprovalRequested */
        EventApprovalRequested: {
            /** At */
            at: string;
            payload: components["schemas"]["ApprovalRequested"];
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "approval.requested";
        };
        /** EventIntentParsed */
        EventIntentParsed: {
            /** At */
            at: string;
            payload: components["schemas"]["IntentParsed"];
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "intent.parsed";
        };
        /** EventInvariantResult */
        EventInvariantResult: {
            /** At */
            at: string;
            payload: components["schemas"]["InvariantResultPayload"];
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "invariant.result";
        };
        /** EventLedgerCompleted */
        EventLedgerCompleted: {
            /** At */
            at: string;
            payload: components["schemas"]["LedgerCompleted"];
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ledger.completed";
        };
        /** EventLedgerPending */
        EventLedgerPending: {
            /** At */
            at: string;
            payload: components["schemas"]["LedgerPending"];
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ledger.pending";
        };
        /** EventPolicyDecided */
        EventPolicyDecided: {
            /** At */
            at: string;
            payload: components["schemas"]["PolicyDecided"];
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "policy.decided";
        };
        /** EventReadbackRecovery */
        EventReadbackRecovery: {
            /** At */
            at: string;
            payload: components["schemas"]["ReadbackRecovery"];
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "readback.recovery";
        };
        /** EventReadbackResult */
        EventReadbackResult: {
            /** At */
            at: string;
            payload: components["schemas"]["ReadbackResultPayload"];
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "readback.result";
        };
        /** EventRenewalInvoice */
        EventRenewalInvoice: {
            /** At */
            at: string;
            payload: components["schemas"]["RenewalInvoice"];
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "renewal.invoice";
        };
        /** EventResolveCompleted */
        EventResolveCompleted: {
            /** At */
            at: string;
            payload: components["schemas"]["ResolveCompleted"];
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "resolve.completed";
        };
        /** EventRunCreated */
        EventRunCreated: {
            /** At */
            at: string;
            payload: components["schemas"]["RunCreated"];
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.created";
        };
        /** EventRunOutcome */
        EventRunOutcome: {
            /** At */
            at: string;
            payload: components["schemas"]["RunOutcomePayload"];
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.outcome";
        };
        /** EventRunStatus */
        EventRunStatus: {
            /** At */
            at: string;
            payload: components["schemas"]["RunStatusPayload"];
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "run.status";
        };
        /** EventSubscriptionMigrated */
        EventSubscriptionMigrated: {
            /** At */
            at: string;
            payload: components["schemas"]["SubscriptionMigrated"];
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "subscription.migrated";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealRequest */
        HealRequest: {
            /** Plan Key */
            plan_key: string;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Apps */
            apps: {
                [key: string]: string;
            };
            /** Commit Sha */
            commit_sha: string;
            /**
             * Db
             * @enum {string}
             */
            db: "ok" | "down";
            /** Ok */
            ok: boolean;
            /**
             * Slack Socket
             * @enum {string}
             */
            slack_socket: "connected" | "down";
            /**
             * Stripe Mode
             * @enum {string}
             */
            stripe_mode: "test" | "unconfigured";
            /** Version */
            version: string;
        };
        /** IntentParsed */
        IntentParsed: {
            /**
             * Interval
             * @enum {string}
             */
            interval: "month" | "year";
            new_amount: components["schemas"]["MoneyModel"];
            /** Plan Hint */
            plan_hint: string;
        };
        /** InvariantResultPayload */
        InvariantResultPayload: {
            /** Detail */
            detail: string;
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "SUCCESS" | "PARTIAL" | "REFUSED" | "NEEDS_HUMAN";
        };
        /** LedgerCompleted */
        LedgerCompleted: {
            /** Entry Hash */
            entry_hash: string;
            /** External Object Id */
            external_object_id: string;
            /** Ledger Id */
            ledger_id: number;
            /** Prev Hash */
            prev_hash: string;
            /** Step No */
            step_no: number;
        };
        /** LedgerPending */
        LedgerPending: {
            /** Action */
            action: string;
            /** App */
            app: string;
            /** Args Hash */
            args_hash: string;
            /** Idempotency Key */
            idempotency_key: string;
            /** Ledger Id */
            ledger_id: number;
            /** Step No */
            step_no: number;
        };
        /** MatchRequest */
        MatchRequest: {
            left: components["schemas"]["PlanSide"];
            right: components["schemas"]["PlanSide"];
        };
        /** MatchResult */
        MatchResult: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "fuzzy" | "human" | "different_currency" | "different_interval";
            /** Detail */
            detail: string;
            /** Match */
            match: boolean;
            /** Score */
            score: number;
            /** Threshold */
            threshold: number;
        };
        /** MoneyModel */
        MoneyModel: {
            /** Currency */
            currency: string;
            /** Minor Units */
            minor_units: number;
        };
        /** PlanSide */
        PlanSide: {
            /** Currency */
            currency: string;
            /**
             * Interval
             * @default
             */
            interval: string;
            /** Label */
            label: string;
        };
        /** PolicyDecided */
        PolicyDecided: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "ALLOW" | "REFUSED" | "NEEDS_HUMAN";
            /** Detail */
            detail: string;
            /** Remedy */
            remedy: string | null;
            /** Rule */
            rule: string;
        };
        /** ReadbackRecovery */
        ReadbackRecovery: {
            /** Call Site */
            call_site: string;
            /** External Object Id */
            external_object_id: string | null;
            /** Found Landed */
            found_landed: boolean;
            /** Ledger Id */
            ledger_id: number;
        };
        /** ReadbackResultPayload */
        ReadbackResultPayload: {
            /** App */
            app: string;
            /** Fresh */
            fresh: boolean;
            /** Raw Value */
            raw_value: string | null;
            /** Read At */
            read_at: string;
            /** Source Id */
            source_id: string;
            value: components["schemas"]["MoneyModel"] | null;
        };
        /** RenewalInvoice */
        RenewalInvoice: {
            amount: components["schemas"]["MoneyModel"];
            /** Invoice Id */
            invoice_id: string;
            /** Test Clock Id */
            test_clock_id: string | null;
        };
        /** ResolveCompleted */
        ResolveCompleted: {
            /** Airtable Record Id */
            airtable_record_id: string | null;
            /** Candidates */
            candidates: components["schemas"]["Candidate"][];
            /** Confidence */
            confidence: number;
            /**
             * Decided By
             * @enum {string}
             */
            decided_by: "exact_id" | "fuzzy" | "human";
            /** Notion Page Id */
            notion_page_id: string | null;
            /** Plan Key */
            plan_key: string | null;
            /** Stripe Price Id */
            stripe_price_id: string | null;
            /** Stripe Product Id */
            stripe_product_id: string | null;
        };
        /** RunCreateRequest */
        RunCreateRequest: {
            /**
             * Approval Mode
             * @description sandbox_auto approves immediately. Requires X-Operator-Token.
             * @default slack
             * @enum {string}
             */
            approval_mode: "slack" | "sandbox_auto";
            /** Change Key */
            change_key?: string | null;
            /**
             * Fault
             * @description Named fault scenario. Requires X-Operator-Token.
             */
            fault?: string | null;
            /** Request Text */
            request_text: string;
        };
        /** RunCreated */
        RunCreated: {
            /** Request Text */
            request_text: string;
        };
        /** RunCreatedResponse */
        RunCreatedResponse: {
            /** Events Url */
            events_url: string;
            /** Run Id */
            run_id: string;
        };
        /** RunOutcomePayload */
        RunOutcomePayload: {
            /** Chain Head */
            chain_head: string;
            /** Invariants Expected */
            invariants_expected: string[];
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "SUCCESS" | "PARTIAL" | "REFUSED" | "NEEDS_HUMAN";
            /** Public Key */
            public_key: string;
            /** Remedy */
            remedy: string | null;
            /** Signature */
            signature: string;
        };
        /** RunStatusPayload */
        RunStatusPayload: {
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "awaiting_human" | "done" | "refused" | "failed";
        };
        /** SandboxRunRequest */
        SandboxRunRequest: {
            /**
             * Scenario
             * @enum {string}
             */
            scenario: "happy_path" | "timeout_after_commit" | "prompt_injection" | "locked_record" | "chain_tamper" | "concurrent_runs" | "drift";
        };
        /** SandboxRunsCreated */
        SandboxRunsCreated: {
            /**
             * Approval Mode
             * @constant
             */
            approval_mode: "sandbox_auto";
            /** Events Urls */
            events_urls: string[];
            /** Run Ids */
            run_ids: string[];
            /** Sandbox Plan Key */
            sandbox_plan_key: string;
        };
        /** SandboxStatus */
        SandboxStatus: {
            /** Available */
            available: boolean;
            /** Cooldown Seconds */
            cooldown_seconds: number;
            /** Queue Depth */
            queue_depth: number;
        };
        /** SubscriptionMigrated */
        SubscriptionMigrated: {
            /** From Price */
            from_price: string;
            /** Proration Behavior */
            proration_behavior: string;
            /** Subscription Id */
            subscription_id: string;
            /** To Price */
            to_price: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_evals_latest_api_evals_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    post_eval_results_api_evals_results_post: {
        parameters: {
            query?: never;
            header?: {
                "x-operator-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalRunIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunRecorded"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ledger_export_api_ledger_export_get: {
        parameters: {
            query?: {
                run_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ledger_verify_api_ledger_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    monitor_events_api_monitor_events_get: {
        parameters: {
            query?: never;
            header?: {
                "last-event-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    monitor_heal_api_monitor_heal_post: {
        parameters: {
            query?: never;
            header?: {
                "x-operator-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HealRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_proof_api_proof_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    public_key_api_public_key_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    resolver_match_api_resolver_match_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: {
                "x-operator-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    operator_approval_api_runs__run_id__approval_post: {
        parameters: {
            query?: never;
            header?: {
                "x-operator-token"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_api_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "last-event-id"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_json_api_runs__run_id__events_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["EventRunCreated"] | components["schemas"]["EventRunStatus"] | components["schemas"]["EventIntentParsed"] | components["schemas"]["EventResolveCompleted"] | components["schemas"]["EventPolicyDecided"] | components["schemas"]["EventApprovalRequested"] | components["schemas"]["EventApprovalDecided"] | components["schemas"]["EventLedgerPending"] | components["schemas"]["EventAdapterFault"] | components["schemas"]["EventReadbackRecovery"] | components["schemas"]["EventLedgerCompleted"] | components["schemas"]["EventSubscriptionMigrated"] | components["schemas"]["EventRenewalInvoice"] | components["schemas"]["EventReadbackResult"] | components["schemas"]["EventInvariantResult"] | components["schemas"]["EventRunOutcome"])[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sandbox_runs_api_sandbox_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SandboxRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxRunsCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sandbox_status_api_sandbox_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxStatus"];
                };
            };
        };
    };
}
